FROM rocker/r-ver:4.4.2

# System dependencies
RUN apt-get update -y && \
    apt-get install -y --no-install-recommends \
        build-essential \
        gcc \
        g++ \
        git \
        libomp-dev && \
    rm -rf /var/lib/apt/lists/*

# R package dependencies
RUN R -e "install.packages(c('remotes', 'rpart', 'rpart.plot', 'MASS'))"
COPY . /tmp/stochtree
RUN R -e "remotes::install_local('/tmp/stochtree')"

# Set working directory
WORKDIR /workspace

# Launch R process
CMD ["R"]