# Generated by cpp11: do not edit by hand

xbart_sample_cpp <- function(model_matrix, param_string) {
  .Call(`_stoch_tree_xbart_sample_cpp`, model_matrix, param_string)
}

xbart_predict_cpp <- function(xbart_ptr, model_matrix, param_string) {
  .Call(`_stoch_tree_xbart_predict_cpp`, xbart_ptr, model_matrix, param_string)
}
