# Generated by cpp11: do not edit by hand

bart_sample_cpp <- function(y, X, omega, rfx_basis, rfx_groups, num_rfx_groups, num_samples, num_burnin, num_trees, nu, lambda, a_rfx, b_rfx, random_seed) {
  .Call(`_stochtree_bart_sample_cpp`, y, X, omega, rfx_basis, rfx_groups, num_rfx_groups, num_samples, num_burnin, num_trees, nu, lambda, a_rfx, b_rfx, random_seed)
}

bart_predict_cpp <- function(bart_ptr, X, omega, rfx_basis, rfx_groups, num_samples) {
  .Call(`_stochtree_bart_predict_cpp`, bart_ptr, X, omega, rfx_basis, rfx_groups, num_samples)
}

xbart_sample_cpp <- function(y, X, omega, rfx_basis, rfx_groups, num_rfx_groups, num_samples, num_burnin, num_trees, nu, lambda, a_leaf, b_leaf, a_rfx, b_rfx, cutpoint_grid_size, random_seed) {
  .Call(`_stochtree_xbart_sample_cpp`, y, X, omega, rfx_basis, rfx_groups, num_rfx_groups, num_samples, num_burnin, num_trees, nu, lambda, a_leaf, b_leaf, a_rfx, b_rfx, cutpoint_grid_size, random_seed)
}

xbart_predict_cpp <- function(xbart_ptr, X, omega, rfx_basis, rfx_groups, num_samples) {
  .Call(`_stochtree_xbart_predict_cpp`, xbart_ptr, X, omega, rfx_basis, rfx_groups, num_samples)
}
